// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validate that URL is actually a valid HTTP/HTTPS URL
const isValidSupabaseUrl = (url: string | undefined): boolean => {
  if (!url) return false;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
};

// Check if Supabase is configured - allows /setup route to work without env vars
export const isSupabaseConfigured = isValidSupabaseUrl(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);

// Create client only if configured, otherwise create a placeholder that will error on use
export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : new Proxy({} as SupabaseClient<Database>, {
      get(_, prop) {
        if (prop === 'then') return undefined; // Allow await checks
        throw new Error(
          'Supabase is not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables.'
        );
      }
    });